# Generated by Django 4.1.6 on 2023-06-01 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_chat_members_chat_member_1_chat_member_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='member_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='member_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
