# Generated by Django 4.1.6 on 2023-06-01 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='member_1',
            field=models.ManyToManyField(related_name='member1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='member_2',
            field=models.ManyToManyField(related_name='member2', to=settings.AUTH_USER_MODEL),
        ),
    ]
